config/routes.rb
Rails.application.routes.draw do

  resources :posts, only: [:edit, :update, :show, :destroy]
  resources :subs do
    resources :posts, only: [:new, :create]
  end
  resources :users
  resource :session, only: [ :new, :create, :destroy ]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, :sub_id, :author_id, presence: true

  belongs_to :author,
    class_name: :User

  belongs_to :sub

  has_many :xposts,
    class_name: :PostSub

  has_many :subs,
    through: :xposts,
    source: :sub
    
end

app/models/post_sub.rb
class PostSub < ApplicationRecord

  validates :sub_id, presence: true

  belongs_to :post

  belongs_to :sub

end

app/models/sub.rb
class Sub < ApplicationRecord
  validates :title, :description, :moderator_id, presence: true

  has_many :posts

  belongs_to :moderator,
    class_name: :User

  has_many :post_subs,
    class_name: :PostSub

  has_many :xposts,
    through: :post_subs,
    source: :post
end

app/models/user.rb
class User < ApplicationRecord

  validates :password, length: { minimum: 6, allow_nil: true }
  validates :username, :password_digest, :session_token, presence: true

  after_initialize :ensure_session_token

  attr_reader :password

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def ensure_session_token
    self.session_token ||= SecureRandom.base64
  end

  def reset_session_token!
    self.session_token = SecureRandom.base64
    self.save!
    self.session_token
  end

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    user && user.is_password?(password) ? user : nil
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def login(user)
    @current_user = user
    session[:session_token] = user.reset_session_token!
  end

  def logout
    current_user.reset_session_token!
    session[:session_token] = nil
    redirect_to new_session_url 
  end

  def logged_in?
    !!current_user
  end

  def require_login
    unless logged_in?
      flash[:errors] = [ "Must be logged in" ]
      redirect_to new_session_url
    end
  end

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_login, only: [:create, :new, :update, :edit, :destroy]

  def show
    @post = Post.find(params[:id])
  end

  def new
  end

  def create
    @post = Post.new(post_params)
    @post.author = current_user
    @post.sub_id = params[:sub_id]
    if @post.save
      redirect_to sub_url(@post.sub)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.author == current_user
      if @post.update(post_params)
        redirect_to sub_url(@post.sub)
      else
        flash.now[:errors] = @post.errors.full_messages
        render :edit
      end
    else
      flash.now[:errors] = ['That is not your post']
      render :edit
    end
  end


  def destroy
    @post = Post.find(params[:id])
    @post.destroy!
    redirect_to sub_url(@post.sub)
  end

  def post_params
    params.require(:post).permit(:title, :url, :content)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    render :new
  end

  def create
    user = User.find_by_credentials(params[:user][:username], params[:user][:password])
    if user
      login(user)
      redirect_to user_url(user)
    else
      flash.now[:errors] = user.errors.full_messages
      render :new
    end
  end

  def destroy
    logout
  end

end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :require_login, only: [:create, :new, :edit, :update]

  def new
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.moderator_id = current_user.id
    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end



  def edit
    @sub = Sub.find(params[:id])
  end

  def update
    @sub = Sub.find(params[:id])
    if @sub.moderator == current_user
      if @sub.update(sub_params)
        redirect_to sub_url(@sub)
      else
        flash.now[:errors] = @sub.errors.full_messages
        render :edit
      end
    else
      flash.now[:errors] = ['That is not your sub']
      render :edit
    end
  end

  def show
    @sub = Sub.find(params[:id])
  end


  def index
    render :index
  end

  private

  def sub_params
    params.require(:sub).permit(:title, :description)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy if @user == current_user
    redirect_to root_url
  end

  def edit
    @user = User.find(params[:id])
    render :edit
  end

  def update
    @user = User.find(params[:id])
    if @user == current_user
      if @user.update(user_params)
        redirect_to user_url(@user)
      else
        flash.now[:errors] = @user.errors.full_messages
        render :edit
      end
    else
      flash.now[:errors] = [ "Cannot edit another user" ]
      render :edit
    end

  end

  def show
    @user = User.find(params[:id])
    render :show 
  end

  def index
    render :index
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedditClone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>

    <% if flash[:errors] %>
    <% flash[:errors].each do |error| %>
     <p><%= error %></p>
    <% end %>
    <% end %>

    <% if logged_in? %>
      <%= current_user.username %>
      <%= button_to 'Sign Out', session_url, method: :delete %>
    <% else %>
      <%= link_to 'Sign In', new_session_url %>
      <%= link_to 'Sign Up', new_user_url %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<form action="<%= post_url(@post) %>" method="post">
  <input type="hidden" name="_method" value="patch">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label>Title
    <input type="text" name="post[title]" value="<%= @post.title %>">
  </label>

  <label>URL
    <input type="text" name="post[url]" value="<%= @post.url %>">
  </label>

  <label>Content
    <input type="text" name="post[content]" value="<%= @post.content %>">
  </label>

  <input type="submit" name="" value="Submit Post">

</form>

app/views/posts/new.html.erb
<h1>Create Post</h1>

<form action="<%= sub_posts_url(params[:sub_id]) %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label>Title
    <input type="text" name="post[title]" value="">
  </label>

  <label>URL
    <input type="text" name="post[url]" value="">
  </label>

  <label>Content
    <input type="text" name="post[content]" value="">
  </label>

  <input type="submit" name="" value="Submit Post">

</form>

app/views/posts/show.html.erb
<h5><%= link_to @post.sub.title, sub_url(@post.sub) %></h5>
<ul>
  <li>Title: <%= @post.title %></li>
  <li>URL: <%= link_to @post.url %></li>
  <li>Content: <%= @post.content %></li>
</ul>


<% if @post.author == current_user %>
  <%= link_to 'Edit Post', edit_post_url(@post) %>
<% end %>

app/views/subs/edit.html.erb
<!-- <h1>Edit <%= @sub.title %></h1>

<form action="<%= sub_url(@sub) %>" method="post">
  <input type="hidden" name="_method" value="patch">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label>Title
    <input type="text" name="sub[title]" value="<%= @sub.title %>">
  </label>
  <label>Description
    <input type="text" name="sub[description]" value="<%= @sub.description %>">
  </label>
  <button>Update Sub</button>
</form> -->

app/views/subs/index.html.erb
<%= link_to 'Create New Sub', new_sub_url %>
<% Sub.all.each do |sub| %>
  <ul>
    <li>
      <%= link_to sub.title, sub_url(sub) %>
    </li>
  </ul>
<% end %>

app/views/subs/new.html.erb
<h1>Create New Sub</h1>

<form action="<%= subs_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label>Title
    <input type="text" name="sub[title]" value="">
  </label>
  <label>Description
    <input type="text" name="sub[description]" value="">
  </label>
  <button>Create Sub</button>
</form>

app/views/subs/show.html.erb
<h3><%= link_to 'Subs', subs_url %></h3>
<h2><%= @sub.title %></h2>
<%= @sub.description %>
<h4><%= link_to 'Create Post', new_sub_post_url(@sub) %></h4>
<h2>Posts</h2>
<% @sub.posts.each do |post| %>
  <ul>
    <%= link_to post.title, post_url(post) %>
  </ul>
<% end %>

app/views/users/edit.html.erb
<h1>Edit User</h1>

<form action="<%= user_url(@user) %>" method="post">
  <input type="hidden" name="_method" value="patch">

  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label>Username
    <input type="text" name="user[username]" value="<%= @user.username %>">
  </label>

  <label>Password
    <input type="password" name="user[password]" value="">
  </label>

  <input type="submit" name="" value="Edit User">

</form>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<form action="<%= users_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label>Username
    <input type="text" name="user[username]" value="">
  </label>

  <label>Password
    <input type="password" name="user[password]" value="">
  </label>

  <input type="submit" name="" value="Sign Up">

</form>

app/views/users/show.html.erb
<%= @user.username %>